[project]
name = "crates-craters"
version = "0.1.0"
requires-python = "==3.12.*"
description = "Monte Carlo Tree Search for Crates and Craters"
readme = "README.md"
dependencies = [
    "gym>=0.26.2",
    "matplotlib>=3.10.0",
    "numpy>=2.2.3",
    "torch>=2.5.1",
]
